
import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "./providers/theme-provider";
import { Recursive } from "next/font/google";
import { Toaster } from "sonner";
import Footer from "@/components/Footer";
import { SiteSettingsProvider } from "./context/SiteSettingsContext";

const recursive = Recursive({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Hinet Soft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="light"
      style={{ colorScheme: "light" }}
      suppressHydrationWarning
    >
      <body className={recursive.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Toaster
            position="bottom-right"
            theme="dark"
            toastOptions={{
              duration: 4000,
              style: {
                padding: "1rem",
                fontSize: "0.95rem",
                fontWeight: "500",
              },
            }}
          />
          <SiteSettingsProvider>
            <Navbar />
            {children}
            <Footer />
          </SiteSettingsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
